name: oauth1
version: 1.0.2
description: "\"RFC 5849: The OAuth 1.0 Protocol\" client implementation for Dart."
homepage: https://github.com/nbspou/dart-oauth1
author: kumar8600 <kumar1@hotmail.co.jp>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  crypto: ^2.0.5
  http: ^0.11.3+16
  uuid: ^1.0.0

dev_dependencies:
  test: ^1.0.0
