name: oauth1
version: 2.0.0
description: "\"RFC 5849: The OAuth 1.0 Protocol\" client implementation for Dart."
homepage: https://github.com/nbspou/dart-oauth1
author: kumar8600 <kumar1@hotmail.co.jp>

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.5
